# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'GoogleAPI' do
    use_frameworks!
    pod 'Alamofire', '~> 4.0'
    pod 'Unbox'
end

target 'GoogleAPITests' do

end

target 'GoogleAPIUITests' do

end

